definitions:
  github_com_oliveirabalsa_go-globalhitss-be_app_model.Client:
    properties:
      active:
        type: boolean
      address:
        type: string
      contact:
        type: string
      cpf:
        type: string
      date_of_birth:
        type: string
      id:
        type: string
      last_name:
        type: string
      name:
        type: string
    required:
    - cpf
    - date_of_birth
    - last_name
    - name
    type: object
info:
  contact: {}
paths:
  /clients:
    get:
      consumes:
      - application/json
      description: Get a list of clients from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_oliveirabalsa_go-globalhitss-be_app_model.Client'
            type: array
      summary: Get a list of clients
      tags:
      - clients
swagger: "2.0"
